In [1]:
#create an evenly spaced array of numbers based on given start and stop values.
#create an array of zeros that be filled with data later.
#create an array of ones.
#craete an array of rando, floats between zero and one.
#Create 1D array and insert the values 1,2,3,4,5 and access the following elements:
        #1st element
        #2nd element
        #range of elements from 1st to 3rd
        #range of elements from 2nd
        #range of elements from index=-2
        
#create 2D array and try to acces following elements:
        #1st row and 2nd column elemnt
        #2nd row elements
        #3rd column elements
        #range of elements in 1st and 2nd row
        #range of elements in 1st and 2nd column
        
#Create a 1D array make it within order by axis wise.
#Read 1D array and insert the values 1,9,2,5,3 and check whether the elements in array are greater than 5. and print those 
#elements as separate list.(use Boolean masking)

In [2]:
import numpy as np

In [14]:
arr1=np.linspace(1,7,5)
arr1

array([1. , 2.5, 4. , 5.5, 7. ])

In [15]:
arr2=np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [16]:
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [17]:
arr4=np.random.rand(4,4)
arr4

array([[0.40081536, 0.07461436, 0.06446567, 0.79864099],
       [0.67237657, 0.00307863, 0.85339561, 0.50219036],
       [0.36826762, 0.64910687, 0.96694172, 0.36526274],
       [0.43364457, 0.55061984, 0.65045184, 0.2452065 ]])

In [20]:
arr5=[1,2,3,4,5]
print('First element: ',arr5[0])

First element:  1


In [21]:
print('Second element: ',arr5[1])

Second element:  2


In [27]:
s=arr5[0]
e=arr5[2]
print('Range of element from 1st to 3rd: ',arr5[0:2])

Range of element from 1st to 3rd:  [1, 2]


In [32]:
e=arr5[1]
print('Range of element from 1st to 3rd: ',arr5[1:])

Range of element from 1st to 3rd:  [2, 3, 4, 5]


In [31]:
print('Range of element from 1st to 3rd: ',arr5[-2])

Range of element from 1st to 3rd:  4


In [39]:
a1=[2,3,4]
a2=[5,1,8]
arr_2D=np.array([a1,a2])
arr_2D


array([[2, 3, 4],
       [5, 1, 8]])

In [38]:
arr_2D
element=arr_2D[0][1]
print('1st row 2nd element: ',element)

1sr row 2nd element:  3


In [40]:
arr_2D
element=arr_2D[1]
print('2nd row elements: ',element)

1sr row 2nd element:  [5 1 8]


In [44]:
arr_2D
element=[row[2] for row in arr_2D]
print('3rd column elements: ',arr_2D[:,2])
#print('3rd column elements: ',element)

3rd column elements:  [4 8]


In [45]:
arr_2D
e=arr_2D[0,:]
s=arr_2D[1,:]
print("Range of elements in 1st and 2nd row: ",arr_2D[e:s])

TypeError: only integer scalar arrays can be converted to a scalar index