In [7]:
import numpy as np
arr=[1,2,3,4,5,6,7,8,9]

np_array=np.array(arr)
np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#2D array

import numpy as np
rows=3
col=3

array_of=[[j for j in range(col)] for i in range(rows)]
array_of

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [11]:
# 3D array

import numpy as np
x=3
y=3
z=3

array_of=[[[j for j in range(x)] for i in range(y)]for k in range(z)]
array_of

[[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]]]

In [12]:
import numpy as np

a1=[1,2,3,4]
a2=[5,6,7,8]
a3=[9,4,6,1]

array_3d=np.array([a1,a2,a3])
array_3d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 6, 1]])

In [13]:
# 4D array

import numpy as np
x=3
y=3
z=3
q=3

array_of=[[[[j for j in range(x)] for i in range(y)]for k in range(z)]for l in range(q)]
array_of

[[[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]]],
 [[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]]],
 [[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
  [[0, 1, 2], [0, 1, 2], [0, 1, 2]]]]

In [14]:
import numpy as np

a1=[1,2,3]
a2=[5,6,7]
a3=[9,4,6]
a4=[8,7,2] 
array_3d=np.array([a1,a2,a3,a4])
array_3d

array([[1, 2, 3],
       [5, 6, 7],
       [9, 4, 6],
       [8, 7, 2]])